config/routes.rb
GrandmasRecipes::Application.routes.draw do
  devise_for :users
  root to: "recipes#index"

  resources :recipes do
    resources :directions
  end

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe

  validates :step_number, numericality: { greater_than: 0 }
  validates :step_number, :description, presence: true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :title, presence: true

  has_many :directions, dependent: :delete_all
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
before_action :set_recipe
before_action :set_direction, only: [:show, :edit, :update, :destroy]

  def new
    @direction = @recipe.directions.build
  end

  def create
    @direction = @recipe.directions.build(direction_params)
    if @direction.save
      flash[:notice] = "Direction has been created."
      redirect_to [@recipe, @direction]
    else
      flash[:alert] = "Direction has not been created."
      render action: "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @direction.update(direction_params)
      flash[:notice] = "Direction has been updated."
      redirect_to [@recipe, @direction]
    else
      flash[:alert] = "Direction has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @direction.destroy
    flash[:notice] = "Direction has been deleted."

    redirect_to @recipe
  end

private
  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def set_direction
    @direction = @recipe.directions.find(params[:id])
  end

  def direction_params
    params.require(:direction).permit(:step_number, :description)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      flash[:notice] = "Recipe has been created."
      redirect_to @recipe
    else
      flash[:alert] = "Recipe has not been created."
      render action: "new"
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:notice] = "Recipe has been updated."
      redirect_to @recipe
    else
      flash[:alert] = "Recipe has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    flash[:notice] = "Recipe has been destroyed."

    redirect_to recipes_path
  end

private
  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, users_attributes: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/directions/_form.html.erb
<%= form_for [@recipe, @direction] do |f| %>
  <% if @direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direction.errors.count, "error") %>
              prohibited this direction from being saved:</h2>
      <ul>
      <% @direction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
   <%= f.label :step_number %><br>
    <%= f.number_field :step_number %>
  </p>

  <p>
   <%= f.label :description %><br>
   <%= f.text_area :description %>
  </p>

  <%= f.submit %>
<% end %>

<p>
  <%= link_to "Back to Recipe", [@recipe] %> |
  <%= link_to "Back to All Recipes", recipes_path %>
</p>

app/views/directions/edit.html.erb
<h2>Editing a direction in <%= @recipe.title %></h2>
<%= render "form" %>

app/views/directions/new.html.erb
<h2>New Direction</h2>
<%= render "form" %>

app/views/directions/show.html.erb
<div id='direction'>
  <h2><%= @direction.step_number %></h2>
  <%= simple_format(@direction.description) %>
  <%= link_to "Edit Direction", [:edit, @recipe, @direction] %> |
  <%= link_to "Delete Direction", [@recipe, @direction], method: :delete,
      data: { confirm: "Are you sure you want to delete this direction?"} %> |
  <%= link_to "Back to Recipe", [@recipe] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grandma's Recipes | by Steph Datu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<nav>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
    (<%= link_to "Sign out", destroy_user_session_path, method: :delete %>)
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recipe.errors.count, "error") %>
             prohibited this recipe from being saved:</h2>
    <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </p>
  <%= f.submit %>
<% end %>

<p>
  <%= link_to "Back to All Recipes", recipes_path %>
</p>

app/views/recipes/edit.html.erb
<h2>Edit recipe</h2>
<%= render "form" %>

app/views/recipes/index.html.erb
<%= link_to "New Recipe", new_recipe_path %>
<br><br>
<h2>Grandma's Recipes</h2>
<p>Your source for all of your favorite recipes!</p>
<br><br>
<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe %></li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h2>New Recipe</h2>

<%= render "form" %>

app/views/recipes/show.html.erb
<h2><%= @recipe.title %></h2>
<p><%= @recipe.ingredients %></p>
<span id='author'>Created by <%= @recipe.user.email if @recipe.user %></span>


<ul id='directions'>
  <% @recipe.directions.each do |direction| %>
    <li>
      #<%= direction.step_number %>:
      <%= link_to simple_format(direction.description), [@recipe, direction] %>
    </li>
  <% end %>
</ul>

<%= link_to "Edit Recipe", edit_recipe_path(@recipe) %> |
<%= link_to "Delete Recipe", recipe_path(@recipe),
    method: :delete,
    data: { confirm: "Are you sure you want to delete this recipe?" } %> |
<%= link_to "New Direction", new_recipe_direction_path(@recipe) %> |
<%= link_to "Back to All Recipes", recipes_path %>